apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: basic-sync
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: basic-sync
    server: {{ .Values.spec.destination.server }}
  project: default
  source:
    path: basic-sync
    repoURL: {{ .Values.spec.source.repoURL }}
    targetRevision: {{ .Values.spec.source.targetRevision }}
